CREATE DATABASE IF NOT EXISTS docutranslate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE docutranslate;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    native_language VARCHAR(100) NOT NULL DEFAULT 'English',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gmail_accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    google_email VARCHAR(255) NOT NULL,
    google_sub VARCHAR(255) DEFAULT NULL,
    access_token TEXT NOT NULL,
    refresh_token TEXT DEFAULT NULL,
    expires_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_user_gmail (user_id),
    CONSTRAINT fk_gmail_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
